package com.EGM.LMS.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * Represents an InstructorProfile entity mapped from the LMS database schema.
 * Stores professional details, localized biographies, and performance analytics.
 */
@Entity
@Table(name = "instructor_profiles")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InstructorProfile {

    /** * Primary Key
     */
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(columnDefinition = "CHAR(36)")
    private UUID id;

    /** * Foreign Key linking to the base User record
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /** * Localized professional headlines (e.g., "Senior Java Architect")
     */
    private String headline;
    private String headlineAm;
    private String headlineOm;
    private String headlineGz;

    /** * DetailedLocalized professional biographies
     */
    private String biography;
    private String biographyAm;
    private String biographyOm;
    private String biographyGz;


    /** * List of instructor skills or areas of expertise stored as JSON
     */
    private String expertise; // Mapped from JSON

    /** * Links to LinkedIn, Twitter, or personal websites stored as JSON
     */
    private String socialLinks; // Mapped from JSON

    /** * Cached total number of students enrolled in this instructor's courses
     */
    private int totalStudents;

    /** * Cached count of published courses
     */
    private int totalCourses;

    /** * Total gross revenue generated by the instructor's content
     */
    private BigDecimal totalRevenue;

    /** * Aggregate rating calculated from student reviews (e.g., 4.8)
     */
    private BigDecimal averageRating;

    /** * Verification flag (TINYINT 1) to show a "Verified" badge
     */
    private boolean isVerified;

    /** * Timestamp of when the instructor passed the verification process
     */
    private LocalDateTime verifiedAt;

    /** * Timestamp of record creation
     */
    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    // --- Standard Constructors, Getters, and Setters ---
}